name: surgical_backend
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - nodejs=18
  - pip
  - pip:
      - python-dotenv==1.0.0
      - websockets==12.0
      - asyncio
      - psycopg2-binary==2.9.9
      - sqlalchemy==2.0.23