version: "3.8"

services:
  backend:
    build: .
    container_name: surgical_backend
    restart: unless-stopped
    environment:
      # All these are now read from the .env file
      - NODE_ENV=${NODE_ENV}
      - PORT=${PORT}
      - DB_HOST=${DB_HOST}
      - DB_PORT=${DB_PORT}
      - DB_NAME=${DB_NAME}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - ULTRALINQ_URL=${ULTRALINQ_URL}
      - ULTRALINQ_USERNAME=${ULTRALINQ_USERNAME}
      - ULTRALINQ_PASSWORD=${ULTRALINQ_PASSWORD}
    ports:
      - "${PORT}:${PORT}"
    networks:
      - app_network

networks:
  app_network:
    driver: bridge
